name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        dotnet build -c Release

    - name: Start EMQ X
      uses: namoshek/emqx-github-action@v1
      with:
        version: '4.2.5'
        ports: '1883:1883 8883:8883'
        certificates: ${{ github.workspace }}/.ci/tls-certificates
        config: ${{ github.workspace }}/.ci/emqx.conf
        container-name: 'mqtt'

    - name: Test
      run: |
        dotnet test -c Release XUnitTestClient/XUnitTestClient.csproj
